export interface InstaUser {
  biography: string,
  businessEmail: string,
  externalUrl: string,
  followedBy: number,
  follow: number,
  fullName: string,
  isBusinessAccount: boolean,
  businessCategoryName: string,
  isPrivate: boolean,
  photoUrl: string,
  username: string,
}

export const categories = [
  'Marketing',
  'Agriculture',
  'Arts and Entertainment',
  'Automotive, Aircraft and Boat',
  'Beauty, Cosmetic and Personal Care',
  'Commercial and Industrial',
  'Education',
  'Finance',
  'Food and Beverage',
  'Hotel and Lodging',
  'Legal',
  'Local Service',
  'Media/News Company',
  'Medical and Health',
  'Non-Government Organization',
  'Nonprofit Organization',
  'Public and Government Services',
  'Real Estate',
  'Science, Technology and Engineering',
  'Shopping and Retail',
  'Sports and Recreation',
  'Travel and Transportation',
] as const;

export type Category = typeof categories[number];